name = "HopfieldDCA"
uuid = "37a64ac8-9262-4a11-880b-74952831694d"
authors = ["Leonardo Di Bari"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
